language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
#  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

before_script:
  - composer install --prefer-source
  - php tests/TradukojConnector/SocketServer/simple-server.php &

after_script:
  - echo "shutdown\n" | nc localhost 13337
  - php vendor/bin/coveralls
